# -*- mode: ruby -*-
# vi: set ft=ruby :
$total = 1

Vagrant.configure(2) do |config|
  (1..$total).each do |i|
    $vm_name = "k8s-node-#{i}"
    config.vm.define "Node-#{i}" do |node|
      node.vm.box = 'local/ubuntu-server-24'                    

      node.vm.hostname = $vm_name           
      node.vm.network "private_network", ip: "192.168.56.11#{i}"

      # node.vm.synced_folder './volume/', '/var/www/public/'

      node.vm.provider "virtualbox" do |vb|
        vb.name = $vm_name
        vb.cpus = 2
        vb.memory = "4096"
      end
    end
  end

config.vm.provision "shell", path: "./bootstrap.sh"

end